import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { NavBar } from "../components/Header/NavBar";
import { TopBar } from "../components/Header/TopBar";
import { ScrollTopButton } from "../components/ScrollTopButton";
import { HtmlPreview } from "../components/admin/HtmlPreview";
import {
  RichTextEditor,
  type PendingEditorImage,
} from "../components/editor/RichTextEditor";
import { apiRequest } from "../services/api";
import type { ArticleSubmissionPublicResponse } from "../types";
import {
  optimizeArticleSubmissionImageFile,
  optimizeAuthorSubmissionPhotoFile,
} from "../utils/imageOptimizer";
import styles from "./VocesSubmission.module.css";
import { useLanguage } from "../i18n/LanguageContext";
import type { Language } from "../i18n/translations";

interface SubmissionForm {
  author_name: string;
  author_lastname: string;
  author_cargo: string;
  author_email: string;
  is_chapter_member: boolean | null;
  title: string;
  subtitle: string;
  body: string;
}

const emptyForm: SubmissionForm = {
  author_name: "",
  author_lastname: "",
  author_cargo: "",
  author_email: "",
  is_chapter_member: null,
  title: "",
  subtitle: "",
  body: "",
};

const SUBMISSION_RULES: Record<
  Language,
  Array<{ title: string; text: string }>
> = {
  es: [
    {
      title: "1. Sé auténtico.",
      text: "El artículo debe ser de autoría propia y no estar generado por inteligencia artificial.",
    },
    {
      title: "2. Usa información confiable.",
      text: "Los datos y afirmaciones deben ser reales y verificables. Cita las fuentes cuando corresponda.",
    },
    {
      title: "3. No hagas publicidad.",
      text: "El artículo no debe utilizarse para promocionar marcas, productos, organizaciones, comunidades o partidos políticos.",
    },
    {
      title: "4. Puedes contar lo que haces.",
      text: "Se permiten artículos sobre proyectos o iniciativas propias cuando busquen compartir experiencias, resultados o aprendizajes, y no hacer publicidad.",
    },
    {
      title: "5. Mantén el respeto.",
      text: "No se aceptará contenido discriminatorio, difamatorio, violento, de odio ni ataques personales.",
    },
    {
      title: "6. Publicamos con criterio editorial.",
      text: "El equipo de Voces podrá solicitar ajustes o rechazar artículos que no cumplan estas reglas o los criterios de calidad de la plataforma.",
    },
  ],

  en: [
    {
      title: "1. Be authentic.",
      text: "The article must be your own work and must not be generated by artificial intelligence.",
    },
    {
      title: "2. Use reliable information.",
      text: "Facts and claims must be real and verifiable. Cite sources whenever appropriate.",
    },
    {
      title: "3. Do not advertise.",
      text: "The article must not be used to promote brands, products, organizations, communities or political parties.",
    },
    {
      title: "4. You can share what you do.",
      text: "Articles about your own projects or initiatives are welcome when they share experiences, results or lessons rather than advertising.",
    },
    {
      title: "5. Be respectful.",
      text: "Discriminatory, defamatory, violent or hateful content, as well as personal attacks, will not be accepted.",
    },
    {
      title: "6. We publish with editorial criteria.",
      text: "The Voices team may request changes or reject articles that do not meet these rules or the platform's quality standards.",
    },
  ],

  it: [
    {
      title: "1. Sii autentico.",
      text: "L'articolo deve essere un'opera originale dell'autore e non deve essere generato dall'intelligenza artificiale.",
    },
    {
      title: "2. Usa informazioni affidabili.",
      text: "Dati e affermazioni devono essere reali e verificabili. Cita le fonti quando necessario.",
    },
    {
      title: "3. Niente pubblicità.",
      text: "L'articolo non deve essere usato per promuovere marchi, prodotti, organizzazioni, comunità o partiti politici.",
    },
    {
      title: "4. Puoi raccontare ciò che fai.",
      text: "Sono ammessi articoli su progetti o iniziative proprie quando condividono esperienze, risultati o apprendimenti e non fanno pubblicità.",
    },
    {
      title: "5. Mantieni il rispetto.",
      text: "Non saranno accettati contenuti discriminatori, diffamatori, violenti o d'odio né attacchi personali.",
    },
    {
      title: "6. Pubblichiamo con criterio editoriale.",
      text: "Il team di Voci può richiedere modifiche o rifiutare articoli che non rispettino queste regole o gli standard di qualità della piattaforma.",
    },
  ],

  pt: [
    {
      title: "1. Seja autêntico.",
      text: "O artigo deve ser de autoria própria e não deve ser gerado por inteligência artificial.",
    },
    {
      title: "2. Use informações confiáveis.",
      text: "Os dados e afirmações devem ser reais e verificáveis. Cite as fontes quando necessário.",
    },
    {
      title: "3. Não faça publicidade.",
      text: "O artigo não deve ser usado para promover marcas, produtos, organizações, comunidades ou partidos políticos.",
    },
    {
      title: "4. Você pode contar o que faz.",
      text: "São permitidos artigos sobre projetos ou iniciativas próprias quando compartilham experiências, resultados ou aprendizados e não fazem publicidade.",
    },
    {
      title: "5. Mantenha o respeito.",
      text: "Não serão aceitos conteúdos discriminatórios, difamatórios, violentos ou de ódio, nem ataques pessoais.",
    },
    {
      title: "6. Publicamos com critério editorial.",
      text: "A equipe de Vozes poderá solicitar ajustes ou rejeitar artigos que não atendam a estas regras ou aos critérios de qualidade da plataforma.",
    },
  ],
};

const SUBMISSION_ERRORS: Record<
  Language,
  {
    photoType: string;
    photoSize: string;
    photoSquare: string;
    photoRead: string;
    acceptRules: string;
    completeFields: string;
    missingImage: string;
    titleLength: string;
    summaryLength: string;
    articleLength: string;
  }
> = {
  es: {
    photoType: "La fotografía debe ser JPG, PNG o WebP.",
    photoSize: "La fotografía original no puede pesar más de 15 MB.",
    photoSquare:
      "La fotografía del autor debe ser cuadrada (misma medida de ancho y alto).",
    photoRead: "No se pudo leer la fotografía seleccionada.",
    acceptRules:
      "Debes leer y aceptar las reglas de publicación antes de enviar tu artículo.",
    completeFields: "Completa todos los campos antes de enviar tu artículo.",
    missingImage:
      "Hay una imagen del artículo que ya no está disponible. Elimínala y vuelve a insertarla.",
    titleLength: "El título debe tener entre 10 y 100 caracteres.",
    summaryLength: "El resumen debe tener entre 40 y 300 caracteres.",
    articleLength: "El contenido debe tener entre 300 y 2,500 palabras.",
  },

  en: {
    photoType: "The photo must be JPG, PNG or WebP.",
    photoSize: "The original photo cannot be larger than 15 MB.",
    photoSquare:
      "The author photo must be square (same width and height).",
    photoRead: "The selected photo could not be read.",
    acceptRules:
      "You must read and accept the publishing rules before submitting your article.",
    completeFields: "Complete all fields before submitting your article.",
    missingImage:
      "An article image is no longer available. Remove it and insert it again.",
    titleLength: "The title must be between 10 and 100 characters.",
    summaryLength: "The summary must be between 40 and 300 characters.",
    articleLength: "The content must be between 300 and 2,500 words.",
  },

  it: {
    photoType: "La foto deve essere JPG, PNG o WebP.",
    photoSize: "La foto originale non può superare 15 MB.",
    photoSquare:
      "La foto dell'autore deve essere quadrata (stessa larghezza e altezza).",
    photoRead: "Non è stato possibile leggere la foto selezionata.",
    acceptRules:
      "Devi leggere e accettare le regole di pubblicazione prima di inviare l'articolo.",
    completeFields: "Completa tutti i campi prima di inviare l'articolo.",
    missingImage:
      "Un'immagine dell'articolo non è più disponibile. Rimuovila e inseriscila nuovamente.",
    titleLength: "Il titolo deve contenere tra 10 e 100 caratteri.",
    summaryLength: "Il riepilogo deve contenere tra 40 e 300 caratteri.",
    articleLength: "Il contenuto deve contenere tra 300 e 2.500 parole.",
  },

  pt: {
    photoType: "A foto deve ser JPG, PNG ou WebP.",
    photoSize: "A foto original não pode ter mais de 15 MB.",
    photoSquare:
      "A foto do autor deve ser quadrada (mesma largura e altura).",
    photoRead: "Não foi possível ler a foto selecionada.",
    acceptRules:
      "Você deve ler e aceitar as regras de publicação antes de enviar seu artigo.",
    completeFields: "Preencha todos os campos antes de enviar seu artigo.",
    missingImage:
      "Uma imagem do artigo não está mais disponível. Remova-a e insira-a novamente.",
    titleLength: "O título deve ter entre 10 e 100 caracteres.",
    summaryLength: "O resumo deve ter entre 40 e 300 caracteres.",
    articleLength: "O conteúdo deve ter entre 300 e 2.500 palavras.",
  },
};

const MAX_LOCAL_IMAGE_BYTES = 15 * 1024 * 1024;

const TITLE_MIN_CHARS = 10;
const TITLE_MAX_CHARS = 100;
const SUMMARY_MIN_CHARS = 40;
const SUMMARY_MAX_CHARS = 300;
const ARTICLE_MIN_WORDS = 300;
const ARTICLE_MAX_WORDS = 2500;

const COUNT_LABELS: Record<
  Language,
  {
    characters: string;
    words: string;
    minimum: string;
  }
> = {
  es: {
    characters: "caracteres",
    words: "palabras",
    minimum: "mínimo",
  },
  en: {
    characters: "characters",
    words: "words",
    minimum: "minimum",
  },
  it: {
    characters: "caratteri",
    words: "parole",
    minimum: "minimo",
  },
  pt: {
    characters: "caracteres",
    words: "palavras",
    minimum: "mínimo",
  },
};

function htmlToPlainText(html: string): string {
  if (!html) return "";

  if (typeof DOMParser === "undefined") {
    return html
      .replace(/<[^>]*>/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  const documentFragment = new DOMParser().parseFromString(
    html,
    "text/html",
  );

  documentFragment
    .querySelectorAll("script, style, noscript, template")
    .forEach((element) => element.remove());

  return (documentFragment.body.textContent ?? "")
    .replace(/\u00a0/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function countPlainCharacters(value: string): number {
  return Array.from(value.trim()).length;
}

function countVisibleWords(html: string): number {
  const text = htmlToPlainText(html);
  return text ? text.split(/\s+/).filter(Boolean).length : 0;
}

function createPendingImageId() {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `article-${crypto.randomUUID()}`;
  }

  return `article-${Date.now()}-${Math.random()
    .toString(36)
    .slice(2, 10)}`;
}

function extractUsedPendingImageIds(html: string): string[] {
  if (!html || typeof DOMParser === "undefined") return [];

  const documentFragment = new DOMParser().parseFromString(
    html,
    "text/html",
  );

  return Array.from(
    documentFragment.querySelectorAll(
      "img[data-pending-image-id]",
    ),
  )
    .map(
      (image) =>
        image.getAttribute("data-pending-image-id") ?? "",
    )
    .filter(Boolean);
}

export default function EnviarArticulo() {
  const { t, language } = useLanguage();

  const submissionRules = SUBMISSION_RULES[language];
  const submissionErrors = SUBMISSION_ERRORS[language];

  const [form, setForm] =
    useState<SubmissionForm>(emptyForm);

  const [authorPhotoFile, setAuthorPhotoFile] =
    useState<File | null>(null);

  const [authorPhotoPreview, setAuthorPhotoPreview] =
    useState("");

  const [articleImages, setArticleImages] = useState<
    PendingEditorImage[]
  >([]);

  const [sending, setSending] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [acceptedRules, setAcceptedRules] =
    useState(false);

  const articleImagesRef =
    useRef<PendingEditorImage[]>([]);

  const authorPhotoPreviewRef = useRef("");

  useEffect(() => {
    articleImagesRef.current = articleImages;
  }, [articleImages]);

  useEffect(() => {
    authorPhotoPreviewRef.current =
      authorPhotoPreview;
  }, [authorPhotoPreview]);

  useEffect(
    () => () => {
      for (const image of articleImagesRef.current) {
        URL.revokeObjectURL(image.previewUrl);
      }

      if (authorPhotoPreviewRef.current) {
        URL.revokeObjectURL(
          authorPhotoPreviewRef.current,
        );
      }
    },
    [],
  );

  useEffect(() => {
    if (!sending) return;

    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      event.preventDefault();
      event.returnValue = "";
    };

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    window.addEventListener("beforeunload", handleBeforeUnload);

    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, [sending]);

  const countLabels = COUNT_LABELS[language];

  const titleLength = countPlainCharacters(form.title);
  const summaryLength = countPlainCharacters(form.subtitle);
  const articleWordCount = useMemo(
    () => countVisibleWords(form.body),
    [form.body],
  );

  const canSend = useMemo(
    () =>
      form.author_name.trim().length > 0 &&
      form.author_lastname.trim().length > 0 &&
      form.author_cargo.trim().length > 0 &&
      form.author_email.trim().length > 0 &&
      form.is_chapter_member !== null &&
      authorPhotoFile !== null &&
      titleLength >= TITLE_MIN_CHARS &&
      titleLength <= TITLE_MAX_CHARS &&
      summaryLength >= SUMMARY_MIN_CHARS &&
      summaryLength <= SUMMARY_MAX_CHARS &&
      articleWordCount >= ARTICLE_MIN_WORDS &&
      articleWordCount <= ARTICLE_MAX_WORDS &&
      acceptedRules,
    [
      form.author_name,
      form.author_lastname,
      form.author_cargo,
      form.author_email,
      form.is_chapter_member,
      authorPhotoFile,
      titleLength,
      summaryLength,
      articleWordCount,
      acceptedRules,
    ],
  );

  const selectAuthorPhoto = async (file: File) => {
    setError("");

    if (
      !file.type.match(/^image\/(jpeg|png|webp)$/)
    ) {
      setError(submissionErrors.photoType);
      return;
    }

    if (file.size > MAX_LOCAL_IMAGE_BYTES) {
      setError(submissionErrors.photoSize);
      return;
    }

    try {
      const dimensions =
        await readImageDimensions(file);

      if (
        dimensions.width !== dimensions.height
      ) {
        setError(submissionErrors.photoSquare);
        return;
      }

      if (authorPhotoPreview) {
        URL.revokeObjectURL(authorPhotoPreview);
      }

      const previewUrl =
        URL.createObjectURL(file);

      setAuthorPhotoFile(file);
      setAuthorPhotoPreview(previewUrl);
    } catch (imageError) {
      setError(
        imageError instanceof Error
          ? imageError.message
          : submissionErrors.photoRead,
      );
    }
  };

  const registerArticleImage = (
    file: File,
  ): PendingEditorImage => {
    const pending: PendingEditorImage = {
      id: createPendingImageId(),
      file,
      previewUrl: URL.createObjectURL(file),
    };

    setArticleImages((current) => [
      ...current,
      pending,
    ]);

    return pending;
  };

  const resetLocalFiles = () => {
    if (authorPhotoPreview) {
      URL.revokeObjectURL(authorPhotoPreview);
    }

    for (const image of articleImages) {
      URL.revokeObjectURL(image.previewUrl);
    }

    setAuthorPhotoFile(null);
    setAuthorPhotoPreview("");
    setArticleImages([]);
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();

    if (!acceptedRules) {
      setError(submissionErrors.acceptRules);
      return;
    }

    if (
      titleLength < TITLE_MIN_CHARS ||
      titleLength > TITLE_MAX_CHARS
    ) {
      setError(submissionErrors.titleLength);
      return;
    }

    if (
      summaryLength < SUMMARY_MIN_CHARS ||
      summaryLength > SUMMARY_MAX_CHARS
    ) {
      setError(submissionErrors.summaryLength);
      return;
    }

    if (
      articleWordCount < ARTICLE_MIN_WORDS ||
      articleWordCount > ARTICLE_MAX_WORDS
    ) {
      setError(submissionErrors.articleLength);
      return;
    }

    if (!canSend || !authorPhotoFile) {
      setError(submissionErrors.completeFields);
      return;
    }

    setSending(true);
    setError("");
    setMessage("");

    try {
      /*
       * Las imágenes permanecen locales mientras el usuario edita.
       * Al enviar, se optimizan y viajan junto con la metadata en un
       * único multipart que el backend convierte a URLs persistentes.
       */
      const optimizedAuthor =
        await optimizeAuthorSubmissionPhotoFile(
          authorPhotoFile,
        );

      const usedIds = new Set(
        extractUsedPendingImageIds(form.body),
      );

      const usedImages = articleImages.filter(
        (image) => usedIds.has(image.id),
      );

      if (usedIds.size !== usedImages.length) {
        throw new Error(
          submissionErrors.missingImage,
        );
      }

      const optimizedArticleImages =
        await Promise.all(
          usedImages.map(async (image) => ({
            id: image.id,
            file: await optimizeArticleSubmissionImageFile(
              image.file,
            ),
          })),
        );

      const payload = new FormData();

      payload.append(
        "metadata",
        JSON.stringify(form),
      );

      payload.append(
        "author_photo",
        optimizedAuthor,
        optimizedAuthor.name,
      );

      for (const image of optimizedArticleImages) {
        payload.append(
          "article_image_ids",
          image.id,
        );
        payload.append(
          "article_images",
          image.file,
          image.file.name,
        );
      }

      const response =
        await apiRequest<ArticleSubmissionPublicResponse>(
          "/article-submissions",
          {
            method: "POST",
            body: payload,
          },
        );

      setMessage(
        response.message ||
          "Tu artículo fue enviado correctamente.",
      );

      resetLocalFiles();
      setForm(emptyForm);
      setAcceptedRules(false);
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "No se pudo enviar el artículo.",
      );
    } finally {
      setSending(false);
    }
  };

  return (
    <>
      <TopBar />
      <NavBar />

      <main className={styles.page}>
        <div className={styles.shell}>
          <Link
            className={styles.back}
            to="/voces"
          >
            ← {t("submission.back")}
          </Link>

          <header className={styles.hero}>
            <span>
              {t("submission.eyebrow")}
            </span>

            <h1>
              {t("submission.title")}
            </h1>

            <p>
              {t("submission.intro")}
            </p>
          </header>

          {message ? (
            <section className={styles.success}>
              <strong>
                {t("submission.received")}
              </strong>

              <p>{message}</p>

              <Link to="/voces">
                {t("submission.back")}
              </Link>
            </section>
          ) : (
            <form
              className={styles.form}
              onSubmit={submit}
            >
              {error && (
                <div className={styles.error}>
                  {error}
                </div>
              )}

              <section className={styles.card}>
                <div
                  className={
                    styles.sectionHeading
                  }
                >
                  <span>01</span>

                  <div>
                    <h2>
                      {t(
                        "submission.rulesTitle",
                      )}
                    </h2>

                    <p>
                      {t(
                        "submission.rulesIntro",
                      )}
                    </p>
                  </div>
                </div>

                <div className={styles.rules}>
                  {submissionRules.map(
                    (rule) => (
                      <p key={rule.title}>
                        <strong>
                          {rule.title}
                        </strong>{" "}
                        {rule.text}
                      </p>
                    ),
                  )}
                </div>
              </section>

              <section className={styles.card}>
                <div
                  className={
                    styles.sectionHeading
                  }
                >
                  <span>02</span>

                  <div>
                    <h2>
                      {t(
                        "submission.aboutYou",
                      )}
                    </h2>

                    <p>
                      {t(
                        "submission.aboutYouIntro",
                      )}
                    </p>
                  </div>
                </div>

                <div
                  className={styles.twoColumns}
                >
                  <Field
                    label={t(
                      "submission.names",
                    )}
                    value={form.author_name}
                    onChange={(author_name) =>
                      setForm({
                        ...form,
                        author_name,
                      })
                    }
                  />

                  <Field
                    label={t(
                      "submission.lastnames",
                    )}
                    value={
                      form.author_lastname
                    }
                    onChange={(
                      author_lastname,
                    ) =>
                      setForm({
                        ...form,
                        author_lastname,
                      })
                    }
                  />
                </div>

                <div
                  className={styles.twoColumns}
                >
                  <Field
                    label={t(
                      "submission.position",
                    )}
                    value={form.author_cargo}
                    onChange={(author_cargo) =>
                      setForm({
                        ...form,
                        author_cargo,
                      })
                    }
                  />

                  <Field
                    label={t(
                      "submission.email",
                    )}
                    type="email"
                    value={form.author_email}
                    onChange={(author_email) =>
                      setForm({
                        ...form,
                        author_email,
                      })
                    }
                  />
                </div>

                <div
                  className={styles.memberField}
                >
                  <span
                    className={
                      styles.memberLabel
                    }
                  >
                    {t(
                      "submission.memberQuestion",
                    )}
                  </span>

                  <div
                    className={
                      styles.memberOptions
                    }
                  >
                    <button
                      type="button"
                      className={
                        form.is_chapter_member ===
                        true
                          ? styles.memberOptionActive
                          : ""
                      }
                      onClick={() =>
                        setForm({
                          ...form,
                          is_chapter_member:
                            true,
                        })
                      }
                    >
                      {t(
                        "submission.yesMember",
                      )}
                    </button>

                    <button
                      type="button"
                      className={
                        form.is_chapter_member ===
                        false
                          ? styles.memberOptionActive
                          : ""
                      }
                      onClick={() =>
                        setForm({
                          ...form,
                          is_chapter_member:
                            false,
                        })
                      }
                    >
                      {t(
                        "submission.noMember",
                      )}
                    </button>
                  </div>

                  <small>
                    {t(
                      "submission.memberPrivate",
                    )}
                  </small>
                </div>

                <div
                  className={styles.photoField}
                >
                  <label>
                    {t(
                      "submission.authorPhoto",
                    )}
                  </label>

                  <p
                    className={
                      styles.photoHelp
                    }
                  >
                    {t(
                      "submission.photoHelp",
                    )}
                  </p>

                  <div
                    className={styles.photoRow}
                  >
                    <label
                      className={
                        styles.uploadButton
                      }
                    >
                      {t(
                        "submission.selectImage",
                      )}

                      <input
                        type="file"
                        accept="image/jpeg,image/png,image/webp"
                        disabled={sending}
                        onChange={(event) => {
                          const file =
                            event.target
                              .files?.[0];

                          if (file) {
                            void selectAuthorPhoto(
                              file,
                            );
                          }

                          event.currentTarget.value =
                            "";
                        }}
                      />
                    </label>

                    <span>
                      {authorPhotoFile
                        ? `${authorPhotoFile.name} · ${t(
                            "submission.photoWillUpload",
                          )}`
                        : t(
                            "submission.photoSpec",
                          )}
                    </span>
                  </div>

                  {authorPhotoPreview && (
                    <img
                      className={
                        styles.photoPreview
                      }
                      src={
                        authorPhotoPreview
                      }
                      alt="Vista previa del autor"
                    />
                  )}
                </div>
              </section>

              <section className={styles.card}>
                <div
                  className={
                    styles.sectionHeading
                  }
                >
                  <span>03</span>

                  <div>
                    <h2>
                      {t(
                        "submission.article",
                      )}
                    </h2>

                    <p>
                      {t(
                        "submission.articleIntro",
                      )}
                    </p>
                  </div>
                </div>

                <Field
                  label={t(
                    "submission.articleTitle",
                  )}
                  value={form.title}
                  maxLength={TITLE_MAX_CHARS}
                  helper={`${titleLength} / ${TITLE_MAX_CHARS} ${countLabels.characters} · ${countLabels.minimum} ${TITLE_MIN_CHARS}`}
                  onChange={(title) =>
                    setForm({
                      ...form,
                      title,
                    })
                  }
                />

                <Field
                  label={t(
                    "submission.subtitle",
                  )}
                  value={form.subtitle}
                  maxLength={SUMMARY_MAX_CHARS}
                  helper={`${summaryLength} / ${SUMMARY_MAX_CHARS} ${countLabels.characters} · ${countLabels.minimum} ${SUMMARY_MIN_CHARS}`}
                  onChange={(subtitle) =>
                    setForm({
                      ...form,
                      subtitle,
                    })
                  }
                />

                <div className={styles.field}>
                  <label>
                    {t(
                      "submission.content",
                    )}
                  </label>

                  <RichTextEditor
                    value={form.body}
                    onChange={(body) =>
                      setForm((current) => ({
                        ...current,
                        body,
                      }))
                    }
                    onRegisterImage={
                      registerArticleImage
                    }
                    placeholder={t(
                      "submission.placeholder",
                    )}
                  />

                  <small
                    className={
                      styles.editorHelp
                    }
                  >
                    {articleWordCount.toLocaleString()} /{" "}
                    {ARTICLE_MAX_WORDS.toLocaleString()} {countLabels.words}
                    {" · "}
                    {countLabels.minimum} {ARTICLE_MIN_WORDS.toLocaleString()}
                  </small>

                  <small
                    className={
                      styles.editorHelp
                    }
                  >
                    {t(
                      "submission.editorHelp",
                    )}
                  </small>
                </div>

                <HtmlPreview
                  value={form.body}
                />
              </section>

              <section
                className={
                  styles.rulesConfirmation
                }
              >
                <label
                  className={
                    styles.rulesAcceptance
                  }
                >
                  <input
                    type="checkbox"
                    checked={acceptedRules}
                    onChange={(event) =>
                      setAcceptedRules(
                        event.target.checked,
                      )
                    }
                  />

                  <span>
                    {t(
                      "submission.accept",
                    )}
                  </span>
                </label>
              </section>

              <div className={styles.submitRow}>
                <p>
                  {t(
                    "submission.submitPending",
                  )}
                </p>

                <button
                  type="submit"
                  disabled={
                    !canSend || sending
                  }
                >
                  {sending
                    ? t(
                        "submission.optimizing",
                      )
                    : t(
                        "submission.send",
                      )}
                </button>
              </div>
            </form>
          )}
        </div>
      </main>

      {sending && (
        <div
          className={styles.sendingOverlay}
          role="status"
          aria-live="assertive"
          aria-busy="true"
        >
          <div className={styles.sendingCard}>
            <div
              className={styles.sendingSpinner}
              aria-hidden="true"
            >
              <span />
            </div>

            <h2>{t("submission.processingTitle")}</h2>

            <p>{t("submission.processingMessage")}</p>

            <div
              className={styles.sendingProgress}
              aria-hidden="true"
            >
              <span />
            </div>

            <strong className={styles.sendingWarning}>
              {t("submission.processingWarning")}
            </strong>

            <small>{t("submission.processingDetail")}</small>
          </div>
        </div>
      )}

      <ScrollTopButton />
    </>
  );
}

function Field({
  label,
  value,
  onChange,
  type = "text",
  maxLength,
  helper,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  type?: string;
  maxLength?: number;
  helper?: string;
}) {
  return (
    <div className={styles.field}>
      <label>{label}</label>

      <input
        required
        type={type}
        value={value}
        maxLength={maxLength}
        onChange={(event) =>
          onChange(event.target.value)
        }
      />

      {helper && (
        <small className={styles.editorHelp}>
          {helper}
        </small>
      )}
    </div>
  );
}

function readImageDimensions(
  file: File,
): Promise<{
  width: number;
  height: number;
}> {
  return new Promise((resolve, reject) => {
    const url =
      URL.createObjectURL(file);

    const image = new Image();

    image.onload = () => {
      const result = {
        width: image.naturalWidth,
        height: image.naturalHeight,
      };

      URL.revokeObjectURL(url);

      resolve(result);
    };

    image.onerror = () => {
      URL.revokeObjectURL(url);

      reject(
        new Error(
          "No se pudo leer la imagen seleccionada.",
        ),
      );
    };

    image.src = url;
  });
}